
categories:
  - title: 'ğŸš€ Features and Improvements'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ğŸŒˆ Documentation Updates'
    labels:
      - 'documentation'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bugfix'
  - title: 'ğŸ§° Breaking Changes'
    label: 'breaking'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bugfix'
      - 'documentation'
  default: patch
tag-template: '$RESOLVED_VERSION'
name-template: 'v$RESOLVED_VERSION'
change-template: '* $TITLE (#$NUMBER)'
change-title-escapes: ''
exclude-labels:
  - 'skip-changelog'
template: |
  ## Whatâ€™s Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
